/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Petpet */

#ifndef _Included_Petpet
#define _Included_Petpet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Petpet
 * Method:    GeneratePetpetToFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Petpet_GeneratePetpetToFile
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
